### ISSUE TITLE
Compilation fails in the start directory

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/guide-jpa-intro#102]
Should I be able to run 'mvn compile' from the start directory?  

When I clone the guide and navigate to the start directory I cannot successfully execute `mvn install` or `mvn compile` because there are compilation errors (see screenshot below).  Perhaps it would be more user friendly and intuitive if the user could compile from the start directory.  Compilation errors should only occur if they are caused by the user.

![image](https://user-images.githubusercontent.com/26146482/56243652-1e700080-6069-11e9-923a-3e50d6314f42.png)

**Comment by justineechen** [comment]
In this case, the compilation errors are due to missing classes that the user will create throughout the guide. To resolve this we may have to give users the start files without these references to the classes that haven't been made yet and ask them to create it but it would be unnecessary work for them to be editing the files that steer away from the focus of the guide. I think since `start` is only the starting point of their application and not necessarily a finished product it's okay to have these compile errors unless we have a better workaround to get rid of the errors. 
@gkwan-ibm

**Comment by gkwan-ibm** [comment]
Will study the possibility to improve the user experience when users run `mvn compile`, `mvn package`, or `mvn install`, etc when the start directory does not create or update the required files by the guide instructions.

**Comment by gkwan-ibm** [comment]
The guide will be updated to use dev mode, then no need to compile
- https://github.com/openliberty/guide-jpa-intro/issues/135

**Comment by gkwan-ibm** [comment]
The guide was updated to use dev mode.
